### PR TITLE
Support for TaHomaUSA

### PR DESCRIPTION
**Pull request by PabloZaiden**

### CODE REVIEW

**Comment by yenoiwesa** [comment]
Hello there @PabloZaiden , thanks for the pull request, much appreciated!

Can you confirm that you were able to make the plugin work in your region with that new service configuration?

**Comment by PabloZaiden** [comment]
Confirmed! I’m currently using it at home with this patch.

**Comment by yenoiwesa** [comment]
Awesome thanks for confirming!

**Comment by yenoiwesa** [comment]
I published version 2.2.0 of the plugin with your change!

**Pull request merged**
